apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: backend-user
          image: harsh3305/hrv-mart-backend-user
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  key: mongodb-uri
                  name: config-map
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: kafka-url
---
apiVersion: v1
kind: Service
metadata:
  name: backend-user-service
spec:
  selector:
    app: user
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000